# Generated by Django 4.2.2 on 2024-03-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sold_id',
            new_name='sold',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
