# Generated by Django 4.2.2 on 2024-03-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_attribute_attributevalue_subcategory_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='code',
        ),
    ]
