# Generated by Django 4.2.2 on 2024-03-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_childproduct_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='temporary_default_sku', max_length=255, unique=True),
        ),
    ]
