# Generated by Django 4.2.2 on 2024-03-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_product_brand_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childproduct',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
